
# Generated by Qodo Gen
from main import prime_number
import unittest

class TestPrimeNumber(unittest.TestCase):

    # Returns False for numbers less than 2
    def test_returns_false_for_numbers_less_than_2(self):
        for number in range(-10, 2):
            with self.subTest(number=number):
                self.assertFalse(prime_number(number))

    # Handles the smallest non-prime number, 0
    def test_handles_smallest_non_prime_number_0(self):
        self.assertFalse(prime_number(0))

    # Handles the smallest prime number, 2
    def test_handles_smallest_prime_number_2(self):
        self.assertTrue(prime_number(2))